### ISSUE TITLE
openapi not working (tried both builder and slimbuilder)

### ISSUE THREAD

**Issue by jkone27** [Lanayx/Oxpecker#25]
maybe did smt wrong, but cannot see endpoints in `/swagger` with this script

```fsharp
// https://github.com/TheAngryByrd/IcedTasks/blob/master/generate-sdk-references.fsx
#nowarn "20" // for OOP/ignore values
#load "runtime-scripts/Microsoft.AspNetCore.App-latest-8.fsx"
#r "nuget: Oxpecker"
#r "nuget: Oxpecker.OpenApi"
#r "nuget: Swashbuckle.AspNetCore "

open Microsoft.AspNetCore.Builder
open Microsoft.Extensions.DependencyInjection
open Oxpecker
open Oxpecker.OpenApi
open Microsoft.Extensions.DependencyInjection
open Microsoft.Extensions.Configuration
open Swashbuckle.AspNetCore.SwaggerGen
open Microsoft.OpenApi.Models


let endpoints = [

    route "/hello" 
        ("Hello World!" |> text)
        |> configureEndpoint _.WithName("Hello")
        |> addOpenApiSimple<unit, string>

    route "/hello-json" 
        ("""{ "Hello": "World!" }""" |> json)
        |> configureEndpoint _.WithName("HelloJson")
        |> addOpenApiSimple<unit, {| Hello: string |}>
]

let configure (builder: WebApplicationBuilder) =
    builder.Services
        .AddRouting()
        .AddOxpecker()
        .AddEndpointsApiExplorer()
        .AddSwaggerGen()
    builder.Build()

let configureApp (app: WebApplication) =
    app.UseRouting()
        .UseOxpecker(endpoints)
        .UseSwagger() // for generating OpenApi spec
        .UseSwaggerUI() // for viewing Swagger UI
    app

let webApp = 
    WebApplication.CreateSlimBuilder()
    |> configure
    |> configureApp

webApp.Run()
```

**Comment by Lanayx** [comment]
@jkone27 Have you check the ASP.NET documentation? https://learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-8.0
The url should be /swagger/v1/swagger.json

**Comment by Lanayx** [comment]
I've just updated [Basic example](https://github.com/Lanayx/Oxpecker/tree/develop/examples/Basic), so Swagger works properly there, you can check. If it doesn't work with your script, it means that something is missing in your` runtime-scripts/Microsoft.AspNetCore.App-latest-8.fsx` file

**Comment by jkone27** [comment]
This is awesome! Thank you✨

**Comment by jkone27** [comment]
fixed when adding the metadata for HTTP method is fixed by adding `GET` to endpoint lists from script above, added script here, thanks for the examples.
https://gist.github.com/jkone27/dee950808063cbd27eff35caa8a2740e

**Comment by Lanayx** [comment]
Thanks for investigation. Indeed, it looks like openapi itself doesn't support "ANY" http method in its spec, so you have to explicitly specify it
