### ISSUE TITLE
eTag caching?

### ISSUE THREAD

**Issue by Thorium** [Lanayx/Oxpecker#36]
Hi, just a quick question:

The readme.md mentions Oxpecker to support eTag caching but doesn't mention compression support.
As far as I understand, the real benefit is when you combine eTag caching first and then compression: With an If-None-Match match, you send 304, and you don't have to compress the sent resource, so you save both compression and network transfer.

If Oxpecker trusts some AspNetCore compression (Brotli/Zip?), how do you configure pipeline registration so that the eTag and compression work "eTag-checking before compression" and not vice versa?

**Comment by Lanayx** [comment]
Hi! The eTag content is a heritage from Giraffe, but I don't think it's somehow related to compression. 

> how do you configure pipeline registration so that the eTag and compression work "eTag-checking before compression" and not vice versa?

So, the existing functionality won't help, because you'd want to put custom eTag related middleware before [Response compression middelware](https://learn.microsoft.com/en-us/aspnet/core/performance/response-compression), while current mechanism is working in the final Oxpecker middeware. 

Still, I don't see much difference, since once you respond with 304 there will be nothing to compress and there will be no overhead at all.

**Comment by Thorium** [comment]
Ok, it seems by default there is no eTag caching although you "can build one" (or just search a AspNetCore/Kestrel/Owin component from Nuget).

The relation to compression is this: eTag is a hash-code over a resource. So (depending your pipeline order) you could do either one:

1. read resource -> compress -> calc hash -> send
2. read resource -> calc hash -> compress -> send

And this question was that if there would have been built-in one, then it should be the second one to avoid time spent in unnecessary compression. But now I think it'll just be user's concern to check.

**Comment by Lanayx** [comment]
I'm not a bug expert in the topic, but it seems we are mixing several terms here, so let me try to clarify this for future.

1. From what I understand eTag is specifically related to _client-side_ caching, so there is nothing to "build" on server side
2. Oxpecker's `ValidatePreconditions` functionality should be called **after** the resource is retrieved and hash calculated. This means that compressing middleware should be correctly placed **before** the Oxpecker's middleware in configuration, so it will start processing the request before Oxpecker and continue processing response after Oxpecker's handler is done. In case 304 is returned from handler there will be nothing to compress.
3. [Server caching middeware](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/middleware) is another thing to consider, but I think it's orthogonal to the eTag check.

**Comment by Thorium** [comment]
Yes, meanwhile eTag caching is "cache on client side", the server still compares if-none-match header and when you have 500k+ users then it starts to became very relevant on web server traffic (for any non-cdn resources).
