### ISSUE TITLE
BindQuery usage with required params

### ISSUE THREAD

**Issue by joprice** [Lanayx/Oxpecker#41]
Is there a way to get `CLIMutable` to treat a field as required? I currently get default values such as `0` for `int`, and `null` for `string`. It would be useful for validation to have that handled by the data definition without runtime errors, if possible.

**Comment by Lanayx** [comment]
Hi! Have you seen [the validation documentation?](https://lanayx.github.io/Oxpecker/src/Oxpecker/#model-validation). It should work for `string`. For `int` you might want use [this SO answer](https://stackoverflow.com/questions/6662976/required-attribute-for-an-integer-value).

**Comment by joprice** [comment]
Oh wow don't know how I overlooked that. I'm also using some "newtype" single element DU wrappers I need to test with those attributes. For now, I created a newtonsoft jobject from the query and parsed it as json using Thoth, which gives me type-based parsing control, but if I can get away with something simpler I'll switch to that.

**Comment by Lanayx** [comment]
Right, the recent validation addition was added specifically with that in mind - to give a simple instrument familiar to many .NET developer allowing quick implementations, while also not preventing to do FP-style validations further on if needed.
