### ISSUE TITLE
Warning about using CEs for DSL

### ISSUE THREAD

**Issue by MangelMaxime** [Lanayx/Oxpecker#5]
Hello,

I discovered this project via a tweet and read the blog post associated.

I wanted to warn you about using CEs for DSL for now as there are knowns performance problems when building complex/nested structure that way.

You can follow the main issue tracking this problem here: https://github.com/dotnet/fsharp/issues/14429

**Comment by Lanayx** [comment]
Thank you for the warning! Fortunately, the library doesn't enforce you to use new CE-based view engine, it's only a default. One can write few lines of code to integrate Feliz, or original Giraffe view engine.

**Comment by MangelMaxime** [comment]
That's true, but from my experience people use what is available out of the box.

Perhaps, it could be possible to add a guide on how to add a new view engine support. This would avoid the need to dig into the library internal and make path for an easier adoption. It is possible that they don't want to rewrite both their handlers and views functions when doing a migration.

**Comment by Lanayx** [comment]
Yes, I'll make sure I'll include the information of how to use an alternative engine, thanks!

**Comment by Lanayx** [comment]
Added warning to the [readme](https://github.com/Lanayx/Oxpecker/blob/develop/src/Oxpecker/README.md), closing the ticket
