### ISSUE TITLE
Multiple Attributes with ViewEngine

### ISSUE THREAD

**Issue by iieiie** [Lanayx/Oxpecker#6]
Hello, this is a question about usage of the ViewEngine. How would you represent more than one attribute using the ViewEngine DSL? Specifically, how would you represent this: `<div id="some-id" class="some-class">...</div>`?

**Comment by Lanayx** [comment]
Hi, this will be 
```fsharp
div(id="some-id", class'="some-class"){ ... }
```

**Comment by iieiie** [comment]
Aha, I missed the `'` in `class'` in my experiment.

**Comment by iieiie** [comment]
I further explorered adding `onclick="alert('This is a popup message!');"`. This time it doesn't seem to work.

![image](https://github.com/Lanayx/Oxpecker/assets/54215921/31db85ab-6251-4ca2-a0d9-25ec1a3fb0b6)

**Comment by iieiie** [comment]
I guess what's needed is a lot of work similar to this: https://github.com/giraffe-fsharp/Giraffe.ViewEngine/blob/467524c5f607619193013a8c5fdc0da4b66c598b/src/Giraffe.ViewEngine/Engine.fs#L247

**Comment by Lanayx** [comment]
@iieiie I didn't include event handlers "by design", since I regard it as antipattern, they should be added through Javascript. Still, you can achieve that by using .attr method, so it will be
```fsharp
div(id="some-id", class'="some-class).attr("onclick", "alert('Hello')") { .. }
```

**Comment by iieiie** [comment]
Good to know. Thanks.

**Comment by iieiie** [comment]
I just noticed this:

![image](https://github.com/Lanayx/Oxpecker/assets/54215921/0b360fe4-5cb0-4674-afd9-e3e0ea82b76a)

It's more of an IDE (Rider) issue and it shows how much toll using CE has taken on the IDE.

**Comment by Lanayx** [comment]
Wanted to give an update, I've added .on method, so the handler looks a bit nicer now
![image](https://github.com/Lanayx/Oxpecker/assets/3329606/ec8bbd8a-5c8f-4643-b329-fe5bb917c31d)
